[package]
name = "tunnelx"
version = "1.0.0"
description = "A desktop platform for managing multiple intranet tunnel providers."
authors = ["xinvexo"]
license = "MIT"
repository = "https://github.com/xinvexo/tunnelx"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "tunnelx_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
tauri-plugin-prevent-default = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml_ng = "0.10"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio"] }
tauri-plugin-sql = { version = "2.4.0", features = ["sqlite"] }
tokio = { version = "1.50.0", features = ["rt-multi-thread", "macros", "time", "io-util", "fs", "net", "sync"] }
uuid = { version = "1.23.0", features = ["v4"] }
thiserror = "2"
reqwest = { version = "0.13", features = ["blocking", "json", "query", "stream", "rustls"] }
futures-util = "0.3"
flate2 = "1"
tar = "0.4"
zip = { version = "2", default-features = false, features = ["deflate"] }
sysinfo = "0.38.4"
libc = "0.2"
sha2 = "0.10"
hex = "0.4"
base64 = "0.22.1"
chrono = { version = "0.4.45", default-features = false, features = ["clock"] }
tunnelx-watchdog-protocol = { path = "../tunnelx-watchdog-protocol" }

[dev-dependencies]
tauri = { version = "2", features = ["test"] }
